contentHome:
  path: /
  defaults: { _controller: 'Content\Controllers\HomePage::index' }

contentHello:
  path: /hello
  defaults: { _controller: 'Content\Controllers\HomePage::hello', name: 'andrey' }

